# Default values for java-web-app.

replicaCount: 2

image:
  repository: 211125460769.dkr.ecr.us-east-1.amazonaws.com/java-web-app
  pullPolicy: Always
  tag: "v10"

imagePullSecrets:
  - name: aws-ecr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx" # Use either `className` or the annotation, not both
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: java-web-app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: java-web-app-tls
      hosts:
        - java-web-app.example.com

# resources: {}
# livenessProbe:
#   httpGet:
#     path: /
#     port: 8080
# readinessProbe:
#   httpGet:
#     path: /
#     port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
