name: Deploy Kubernetes Application with Helm

on:
    pull_request: 
    workflow_dispatch: 
      inputs:
        image_tag:
          description: 'Docker image tag'
          required: true
        aws_role_arn:
          description: 'AWS IAM role ARN'
          required: true
        aws_region:
          description: 'AWS region'
          required: true
        ecr_repository_name:
          description: 'ECR repository name'
          required: true
        docker_repository:
          description: 'Docker repository'
          required: true
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash


      - name: Lint Helm Chart
        run: |
          helm lint ./java-web-app/.


      - name: Deploy Helm Chart
        run: |
          helm upgrade --install java-web-app ./java-web-app/. \
          --namespace my-namespace \
          --create-namespace \
          --set image.repository=${{ secrets.DOCKER_REPOSITORY }} \
          --set image.tag=${{ secrets.image_tag }} \


      - name: Verify Deployment
        run: |
          kubectl get all -n my-namespace
